routes/web.php
<?php

use App\Http\Controllers\Backend\ArticleController;
use App\Http\Controllers\Backend\DashboardController;
use App\Http\Controllers\Backend\LoginController;
use App\Http\Controllers\Backend\RubricController;
use App\Http\Controllers\Backend\UserController;
use App\Http\Controllers\Frontend\FrontendController;
use Illuminate\Support\Facades\Route;

Route::get("/", [FrontendController::class, "index"])->name("frontpage");
Route::get("/rubric/{rubric}", [FrontendController::class, "rubric"])->name("rubric");
Route::get("/article/{article}", [FrontendController::class, "article"])->name("article");
Route::any("/search", [FrontendController::class, "search"])->name("search");
Route::post("/comment", [FrontendController::class, "storeComment"])->name("comment.store");

/**
 * admin
 */
Route::group(["prefix" => "admin", "as" => "admin."], function () {
    Route::get("", [LoginController::class, "form"])->name("form");
    Route::post("", [LoginController::class, "login"])->name("login");
    Route::group(["middleware" => ["admin"]], function () {
        Route::get("dashboard", DashboardController::class)->name("dashboard");
        Route::get("logout", [LoginController::class, "logout"])->name("logout");
        Route::resource("article", ArticleController::class)->except("show");
        Route::put("article/{article}/restore", [ArticleController::class, "restore"])->name("article.restore");
        Route::group(["middleware" => ["editor"]], function () {
            Route::resource("rubric", RubricController::class)->except("show");
            Route::put("rubric/{rubric}/restore", [RubricController::class, "restore"])->name("rubric.restore");
            Route::group(["middleware" => ["kubik"]], function () {
                Route::resource("user", UserController::class)->except("show");
            });
        });
    });
});

app/Models/Article.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Concerns\HasUuids;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Illuminate\Database\Eloquent\Relations\HasMany;
use Illuminate\Database\Eloquent\Relations\MorphMany;
use Illuminate\Database\Eloquent\Relations\MorphOne;
use Illuminate\Database\Eloquent\SoftDeletes;
use Illuminate\Support\Collection;

/**
 * @property string id
 * @property string name
 * @property string description
 * @property string content
 * @property string rubric_id
 * @property Collection comments
 * @property Collection images
 * @property Image cover
 */
class Article extends Model
{
    use HasFactory, HasUuids, SoftDeletes;

    public function rubric(): BelongsTo
    {
        return $this->belongsTo(Rubric::class);
    }

    public function comments(): HasMany
    {
        return $this->hasMany(Comment::class)->latest();
    }

    public function author(): BelongsTo
    {
        return $this->belongsTo(User::class, "user_id");
    }

    public function images(): MorphMany
    {
        return $this->morphMany(Image::class, "content");
    }

    public function cover(): MorphOne
    {
        return $this->morphOne(Image::class, "content")->where("is_cover", true);
    }

    public function url(): string
    {
        return route("article", $this);
    }

    public function hasImages(): bool
    {
        return $this->images()->count() > 0;
    }
}

app/Http/Controllers/Backend/ArticleController.php
<?php

namespace App\Http\Controllers\Backend;

use App\Enums\Role;
use App\Http\Controllers\Controller;
use App\Http\Requests\Backend\Article\CreateRequest;
use App\Http\Requests\Backend\Article\DeleteRequest;
use App\Http\Requests\Backend\Article\RestoreRequest;
use App\Http\Requests\Backend\Article\UpdateRequest;
use App\Models\Article;
use App\Models\Image;
use App\Models\Rubric;
use Illuminate\Contracts\View\View;
use Illuminate\Database\Eloquent\Builder;
use Illuminate\Http\RedirectResponse;
use Illuminate\Http\UploadedFile;
use Illuminate\Support\Facades\Storage;
use Illuminate\Support\Str;

class ArticleController extends Controller
{

    public function index(): View
    {
        $user = auth()->user();

        $articles = Article::query()
            ->when($user->role === Role::EDITOR, function (Builder $builder) use ($user) {
                return $builder->where("user_id", "=", $user->id);
            })
            ->when($user->role === Role::KUBIK, function (Builder $builder) {
                return $builder->onlyTrashed();
            })
            ->where(fn(Builder $builder) => $builder
                ->where("name", "ilike", "%" . request("q", "") . "%")
                ->orWhere("description", "ilike", "%" . request("q", "") . "%")
                ->orWhere("content", "ilike", "%" . request("q", "") . "%"))
            ->with(["rubric:id,name", "author:id,name"])
            ->withCount("comments")
            ->latest()
            ->paginate(20)
            ->appends(["q" => request("q")]);

        return view("backend.article.index", compact("articles", "user"));
    }


    public function create(): View
    {
        $rubrics = Rubric::query()->orderBy("name")->get();

        return view("backend.article.create", compact("rubrics"));
    }

    public function store(CreateRequest $request): RedirectResponse
    {
        $article              = new Article();
        $article->user_id     = auth()->id();
        $article->name        = $request->validated("name");
        $article->rubric_id   = $request->validated("rubric_id");
        $article->description = $request->validated("description");
        $article->content     = $request->validated("content");
        $article->save();

        $this->uploadImages($article, $request->file("images"));

        return redirect()
            ->route("admin.article.index")
            ->with("success", "Article has been created successfully");
    }


    public function edit(Article $article): View
    {
        $rubrics = Rubric::query()->orderBy("name")->get();
        $article->load("images");

        return view("backend.article.edit", compact("article", "rubrics"));
    }


    public function update(UpdateRequest $request, string $article): RedirectResponse
    {
        $article              = Article::find($article);
        $article->name        = $request->validated("name");
        $article->rubric_id   = $request->validated("rubric_id");
        $article->description = $request->validated("description");
        $article->content     = $request->validated("content");
        $article->save();

        $this->uploadImages($article, $request->file("images"));

        if (!is_null($request->get("cover"))) {
            $article->images()->update(["is_cover" => false]);
            $article->images()->find($request->get("cover"))->update(["is_cover" => true]);
        }

        return redirect()
            ->route("admin.article.edit", $article)
            ->with("success", "Article has been updated successfully");
    }


    public function destroy(DeleteRequest $request): RedirectResponse
    {
        Article::find($request->validated("id"))->delete();

        return redirect()
            ->route("admin.article.index")
            ->with("success", "Article has been deleted successfully");
    }


    public function restore(RestoreRequest $request): RedirectResponse
    {
        Article::withTrashed()->find($request->validated("id"))->restore();

        return redirect()
            ->route("admin.article.index")
            ->with("success", "Article has been restored successfully");
    }

    private function uploadImages(Article $article, ?array $files): void
    {
        if (is_null($files)) {
            return;
        }
        $storage = Storage::disk("images");

        $storage->makeDirectory($article->id);

        collect($files)->each(function (?UploadedFile $file) use ($storage, $article) {
            $fileName = Str::of(Str::random(24))->lower()->toString() . "." . $file->clientExtension();
            $storage->put($article->id . "/" . $fileName, $file->getContent());

            $image           = new Image();
            $image->filename = $fileName;

            $article->images()->save($image);
        });
    }
}

app/Http/Controllers/Backend/DashboardController.php
<?php

namespace App\Http\Controllers\Backend;

use App\Http\Controllers\Controller;
use App\Models\User;
use Illuminate\Contracts\View\View;
use Illuminate\Database\Eloquent\Builder;
use Illuminate\Http\Request;

class DashboardController extends Controller
{
    public function __invoke(Request $request): View
    {
        $users = User::query()
            ->withCount([
                "articles",
                "articles as articles_deleted_count" => function (Builder $builder) {
                    return $builder->onlyTrashed();
                }
            ])
            ->orderByDesc("articles_count")
            ->take(10)
            ->get();
        return view("backend.dashboard", ["user" => $request->user(), "users" => $users]);
    }
}

app/Http/Controllers/Backend/LoginController.php
<?php

namespace App\Http\Controllers\Backend;

use App\Http\Controllers\Controller;
use App\Http\Requests\Backend\LoginRequest;
use App\Models\User;
use Illuminate\Contracts\View\View;
use Illuminate\Http\RedirectResponse;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Hash;

class LoginController extends Controller
{

    public function form(): View
    {
        return view("backend.login.login");
    }

    public function login(LoginRequest $request): RedirectResponse
    {
        /** @var User $user */
        $user = User::query()->where("email", $request->validated("email"))->first();
        if (is_null($user) || !Hash::check($request->validated("password"), $user->password)) {
            return redirect()
                ->route("admin.form")
                ->withInput(["email" => $request->validated("email")])
                ->with("error", "Invalid credentials");
        }
        Auth::login($user);

        return redirect()->route("admin.dashboard");
    }

    public function logout(): RedirectResponse
    {
        Auth::logout();

        return redirect()->route("admin.form");
    }
}

app/Http/Controllers/Backend/RubricController.php
<?php

namespace App\Http\Controllers\Backend;

use App\Enums\Role;
use App\Http\Controllers\Controller;
use App\Http\Requests\Backend\Rubric\CreateRequest;
use App\Http\Requests\Backend\Rubric\DeleteRequest;
use App\Http\Requests\Backend\Rubric\RestoreRequest;
use App\Http\Requests\Backend\Rubric\UpdateRequest;
use App\Models\Rubric;
use Illuminate\Contracts\View\View;
use Illuminate\Database\Eloquent\Builder;
use Illuminate\Http\RedirectResponse;

class RubricController extends Controller
{
    public function index(): View
    {
        $user = auth()->user();

        $rubrics = Rubric::query()
            ->when($user->role === Role::KUBIK, function (Builder $builder) {
                return $builder->onlyTrashed();
            })
            ->where("name", "ilike", "%" . request("q", "") . "%")
            ->withCount("articles")
            ->latest()
            ->paginate(10)
            ->appends(["q" => request("q")]);

        return view("backend.rubric.index", compact("rubrics", "user"));
    }

    public function create(): View
    {
        return view("backend.rubric.create");
    }

    public function store(CreateRequest $request): RedirectResponse
    {
        $rubric       = new Rubric();
        $rubric->name = $request->validated("name");
        $rubric->save();

        return redirect()
            ->route("admin.rubric.index")
            ->with("success", "Rubric has been created successfully");
    }

    public function edit(Rubric $rubric): View
    {
        return view("backend.rubric.edit", compact("rubric"));
    }

    public function update(UpdateRequest $request, string $rubric): RedirectResponse
    {
        $rubric       = Rubric::find($rubric);
        $rubric->name = $request->validated("name");
        $rubric->save();

        return redirect()
            ->route("admin.rubric.edit", $rubric)
            ->with("success", "Rubric has been updated successfully");
    }

    public function destroy(DeleteRequest $request): RedirectResponse
    {
        $rubric = Rubric::find($request->validated("id"));
        $rubric->articles()->delete();
        $rubric->delete();

        return redirect()
            ->route("admin.rubric.index")
            ->with("success", "Rubric has been deleted successfully");
    }

    public function restore(RestoreRequest $request): RedirectResponse
    {
        Rubric::withTrashed()->find($request->validated("id"))->restore();

        return redirect()
            ->route("admin.rubric.index")
            ->with("success", "Rubric has been restored successfully");
    }
}

app/Http/Controllers/Backend/UserController.php
<?php

namespace App\Http\Controllers\Backend;

use App\Enums\Role;
use App\Http\Controllers\Controller;
use App\Http\Requests\Backend\User\CreateRequest;
use App\Http\Requests\Backend\User\UpdateRequest;
use App\Models\User;
use Illuminate\Contracts\View\View;
use Illuminate\Http\RedirectResponse;

class UserController extends Controller
{

    public function index(): View
    {
        $users = User::query()
            ->where("name", "ilike", "%" . request("q", "") . "%")
            ->latest()
            ->paginate(10)
            ->appends(["q" => request("q")]);

        return view("backend.user.index", compact("users"));
    }

    public function create(): View
    {
        return view("backend.user.create", [
            "roles" => Role::cases()
        ]);
    }

    public function store(CreateRequest $request): RedirectResponse
    {
        $user           = new User();
        $user->name     = $request->validated("name");
        $user->email    = $request->validated("email");
        $user->role     = $request->validated("role");
        $user->password = bcrypt($request->validated("password"));
        $user->save();

        return redirect()
            ->route("admin.user.index")
            ->with("success", "User has been created successfully");
    }

    public function edit(User $user): View
    {
        return view("backend.user.edit", [
            "user"  => $user,
            "roles" => Role::cases()
        ]);
    }

    public function update(UpdateRequest $request, string $user): RedirectResponse
    {
        $user        = User::find($user);
        $user->name  = $request->validated("name");
        $user->email = $request->validated("email");
        $user->role  = $request->validated("role");
        if ($request->filled("password")) {
            $user->password = bcrypt($request->validated("password"));
        }
        $user->save();

        return redirect()
            ->route("admin.user.index")
            ->with("success", "User has been updated successfully");
    }

    public function destroy(User $user): RedirectResponse
    {
        $user->delete();

        return redirect()
            ->route("admin.user.index")
            ->with("success", "User has been deleted successfully");
    }
}

resources/views/backend/article/create.blade.php
@extends("backend.layout")

@section("title","Create new article")

@section("content")
    <form action="{{ route("admin.article.store") }}" method="post" enctype="multipart/form-data">
        @csrf
        <div class="form-group">
            <label for="name">Name</label>
            <input type="text" name="name" class="form-control" id="name" placeholder="Enter name"
                   value="{{ old("name") }}">
        </div>

        <div class="form-group">
            <label for="rubric_id">Choose the rubric for the article</label>
            <select type="select" name="rubric_id" class="form-control" id="rubric_id">
                @foreach($rubrics as $rubric)
                    <option value="{{ $rubric->id }}">{{ $rubric->name }}</option>
                @endforeach
            </select>
        </div>

        <div class="form-group">
            <label for="description">Description</label>
            <input type="text" name="description" class="form-control" id="description"
                   placeholder="Enter description" value="{{ old("description") }}">
        </div>
        <div class="form-group">
            <label for="images">Images</label>
            <input type="file" multiple name="images[]" accept="image/*" class="form-control" id="images">
        </div>
        <div class="form-group">
            <label for="content">Content</label>
            <textarea name="content" rows="7" class="form-control" id="content"
                      placeholder="Enter content" value="{{ old("content") }}"></textarea>
        </div>
        <div class="form-group">
            <button type="submit" class="btn btn-success">
                Save
            </button>
        </div>
    </form>
@endsection

resources/views/backend/article/edit.blade.php
@extends("backend.layout")

@section("title","Edit article ".$article->name)

@section("content")
    <form action="{{ route("admin.article.update", $article) }}" method="post">
        @method("put")
        @csrf
        <div class="form-group">
            <label for="name">Name</label>
            <input type="text" name="name" class="form-control" value="{{ $article->name }}" placeholder="Enter name">
        </div>

        <div class="form-group">
            <label for="rubric_id">Choose the rubric for the article</label>
            <select type="select" name="rubric_id" class="form-control" value="{{ $article->rubric_id }}">
                @foreach($rubrics as $rubric)
                    <option
                        value="{{ $rubric->id }}" {{ $article->rubric_id === $rubric->id ? "selected" : "" }}>{{ $rubric->name }}</option>
                @endforeach
            </select>
        </div>

        <div class="form-group">
            <label for="description">Description</label>
            <input name="description" class="form-control" value="{{ $article->description }}"
                   placeholder="Enter description">
        </div>
        <div class="form-group">
            <label for="images">Images</label>
            <input type="file" multiple name="images[]" accept="image/*" class="form-control" id="images">
        </div>
        <div class="form-group">
            <label for="images">Cover</label>
            <div class="row">
                @forelse($article->images as $image)
                    <div class="col-3">
                        <label>
                            <img src="{{ $image->getUrl() }}" alt=""
                                 class="img-thumbnail @if($image->is_cover) bg-primary @endif ">
                            <input type="radio" class="hidd" name="cover"
                                   value="{{ $image->id }}" @checked($image->is_cover) />
                        </label>
                    </div>
                @empty
                    <div class="col-12 text-center text-danger">
                        Nothing uploaded
                    </div>
                @endforelse
            </div>
        </div>
        <div class="form-group">
            <label for="content">Content</label>
            <textarea rows="7" name="content" class="form-control" value="{{ $article->content }}"
                      placeholder="Enter content">{{ $article->content }}
            </textarea>
        </div>
        <div class="form-group">
            <button type="submit" class="btn btn-success">
                Update
            </button>
        </div>
    </form>
@endsection

resources/views/backend/article/index.blade.php
@extends("backend.layout")


@section("title","Articles")


@section("content")
    <div class="row">
        <div class="col-10">
            <form class="form-inline" action="" method="get">
                <input type="text" name="q" value="{{ request("q") }}" class="form-control mb-2 mr-sm-2"
                       placeholder="Search request">
                <button type="submit" class="btn btn-primary mb-2">Search</button>
            </form>
        </div>
        @can("article-add")
            <div class="col-2 text-right">
                <a href="{{ route("admin.article.create") }}" class="btn btn-success">Create new</a>
            </div>
        @endcan
    </div>
    <table class="table table-striped table-sm table-hover table-bordered">
        <thead>
        <tr>
            <th width="41%">Name</th>
            <th width="31%">Rubric</th>
            @can("see-author")
                <th width="10%">Author</th>
            @endcan
            <th width="3%">Comments</th>
            <th width="10%">Created at</th>
            @can("can-restore")
                <th width="10%">Restore</th>
            @endcan
            @can("article-add")
                <th width="5%" colspan="2"></th>
            @endcan
        </tr>
        </thead>
        <tbody>
        @forelse($articles as $article)
            <tr>
                <td><a href="{{ $article->url() }}" target="_blank">{{ $article->name }}</a></td>
                @if($article->rubric)
                    <td><a href="{{ route("rubric", $article->rubric_id) }}">{{ $article->rubric->name }}</a></td>
                @else
                    <td>Rubric deleted</td>
                @endif
                @can("see-author")
                    <td>{{ $article->author->name }}</td>
                @endcan
                <td>{{ $article->comments_count }}</td>
                <td>{{ $article->created_at }}</td>
                @can("can-restore")
                    <td width="50px">
                        <form action="{{ route("admin.article.restore", $article) }}" method="post" class="form-inline">
                            @method("put")
                            @csrf
                            <button type="submit" class="btn btn-sm btn-primary">Restore</button>
                        </form>
                    </td>
                @endcan
                @can("article-edit")
                    <td width="50px">
                        <a href="{{ route("admin.article.edit", $article) }}" class="btn btn-sm btn-primary">Edit</a>
                    </td>
                @endcan
                @can("article-delete")
                    <td width="50px">
                        <form action="{{ route("admin.article.destroy", $article) }}" method="post" class="form-inline">
                            @method("DELETE")
                            @csrf
                            <button type="submit" class="btn btn-sm btn-danger">Delete</button>
                        </form>
                    </td>
                @endcan
            </tr>
        @empty
            <tr>
                <td colspan="5">
                    <h3 class="text-center text-danger">
                        Nothing found for your request
                    </h3>
                </td>
            </tr>
        @endforelse

        </tbody>
    </table>
    <div class="pagination pagination-seperated ">
        {{ $articles->links() }}
    </div>
@endsection