routes/web.php
<?php

use App\Http\Controllers\Backend\ArticleController;
use App\Http\Controllers\Backend\DashboardController;
use App\Http\Controllers\Backend\LoginController;
use App\Http\Controllers\Backend\RubricController;
use App\Http\Controllers\Backend\UserController;
use App\Http\Controllers\Frontend\FrontendController;
use Illuminate\Support\Facades\Route;

Route::get("/", [FrontendController::class, "index"])->name("frontpage");
Route::get("/rubric/{rubric}", [FrontendController::class, "rubric"])->name("rubric");
Route::get("/article/{article}", [FrontendController::class, "article"])->name("article");
Route::any("/search", [FrontendController::class, "search"])->name("search");
Route::post("/comment", [FrontendController::class, "storeComment"])->name("comment.store");

/**
 * admin
 */
Route::group(["prefix" => "admin", "as" => "admin."], function () {
    Route::get("", [LoginController::class, "form"])->name("form");
    Route::post("", [LoginController::class, "login"])->name("login");
    Route::group(["middleware" => ["admin"]], function () {
        Route::get("dashboard", DashboardController::class)->name("dashboard");
        Route::get("logout", [LoginController::class, "logout"])->name("logout");
        Route::resource("article", ArticleController::class)->except("show");
        Route::put("article/{article}/restore", [ArticleController::class, "restore"])->name("article.restore");
        Route::group(["middleware" => ["editor"]], function () {
            Route::resource("rubric", RubricController::class)->except("show");
            Route::put("rubric/{rubric}/restore", [RubricController::class, "restore"])->name("rubric.restore");
            Route::group(["middleware" => ["kubik"]], function () {
                Route::resource("user", UserController::class)->except("show");
            });
        });
    });
});

app/Http/Controllers/Backend/ArticleController.php
<?php

namespace App\Http\Controllers\Backend;

use App\Enums\Role;
use App\Http\Controllers\Controller;
use App\Http\Requests\Backend\Article\CreateRequest;
use App\Http\Requests\Backend\Article\DeleteRequest;
use App\Http\Requests\Backend\Article\RestoreRequest;
use App\Http\Requests\Backend\Article\UpdateRequest;
use App\Models\Article;
use App\Models\Image;
use App\Models\Rubric;
use Illuminate\Contracts\View\View;
use Illuminate\Database\Eloquent\Builder;
use Illuminate\Http\RedirectResponse;
use Illuminate\Http\UploadedFile;
use Illuminate\Support\Facades\Storage;
use Illuminate\Support\Str;

class ArticleController extends Controller
{

    public function index(): View
    {
        $user = auth()->user();

        $articles = Article::query()
            ->when($user->role === Role::EDITOR, function (Builder $builder) use ($user) {
                return $builder->where("user_id", "=", $user->id);
            })
            ->when($user->role === Role::KUBIK, function (Builder $builder) {
                return $builder->onlyTrashed();
            })
            ->where(fn(Builder $builder) => $builder
                ->where("name", "ilike", "%" . request("q", "") . "%")
                ->orWhere("description", "ilike", "%" . request("q", "") . "%")
                ->orWhere("content", "ilike", "%" . request("q", "") . "%"))
            ->with(["rubric:id,name", "author:id,name"])
            ->withCount("comments")
            ->latest()
            ->paginate(20)
            ->appends(["q" => request("q")]);

        return view("backend.article.index", compact("articles", "user"));
    }


    public function create(): View
    {
        $rubrics = Rubric::query()->orderBy("name")->get();

        return view("backend.article.create", compact("rubrics"));
    }

    public function store(CreateRequest $request): RedirectResponse
    {
        $article              = new Article();
        $article->user_id     = auth()->id();
        $article->name        = $request->validated("name");
        $article->rubric_id   = $request->validated("rubric_id");
        $article->description = $request->validated("description");
        $article->content     = $request->validated("content");
        $article->save();

        $this->uploadImages($article, $request->file("images"));

        return redirect()
            ->route("admin.article.index")
            ->with("success", "Article has been created successfully");
    }


    public function edit(Article $article): View
    {
        $rubrics = Rubric::query()->orderBy("name")->get();
        $article->load("images");

        return view("backend.article.edit", compact("article", "rubrics"));
    }


    public function update(UpdateRequest $request, string $article): RedirectResponse
    {
        $article              = Article::find($article);
        $article->name        = $request->validated("name");
        $article->rubric_id   = $request->validated("rubric_id");
        $article->description = $request->validated("description");
        $article->content     = $request->validated("content");
        $article->save();

        $this->uploadImages($article, $request->file("images"));

        if (!is_null($request->get("cover"))) {
            $article->images()->update(["is_cover" => false]);
            $article->images()->find($request->get("cover"))->update(["is_cover" => true]);
        }

        return redirect()
            ->route("admin.article.edit", $article)
            ->with("success", "Article has been updated successfully");
    }


    public function destroy(DeleteRequest $request): RedirectResponse
    {
        Article::find($request->validated("id"))->delete();

        return redirect()
            ->route("admin.article.index")
            ->with("success", "Article has been deleted successfully");
    }


    public function restore(RestoreRequest $request): RedirectResponse
    {
        Article::withTrashed()->find($request->validated("id"))->restore();

        return redirect()
            ->route("admin.article.index")
            ->with("success", "Article has been restored successfully");
    }

    private function uploadImages(Article $article, ?array $files): void
    {
        if (is_null($files)) {
            return;
        }
        $storage = Storage::disk("images");

        $storage->makeDirectory($article->id);

        collect($files)->each(function (?UploadedFile $file) use ($storage, $article) {
            $fileName = Str::of(Str::random(24))->lower()->toString() . "." . $file->clientExtension();
            $storage->put($article->id . "/" . $fileName, $file->getContent());

            $image           = new Image();
            $image->filename = $fileName;

            $article->images()->save($image);
        });
    }
}

app/Http/Controllers/Backend/DashboardController.php
<?php

namespace App\Http\Controllers\Backend;

use App\Http\Controllers\Controller;
use App\Models\User;
use Illuminate\Contracts\View\View;
use Illuminate\Database\Eloquent\Builder;
use Illuminate\Http\Request;

class DashboardController extends Controller
{
    public function __invoke(Request $request): View
    {
        $users = User::query()
            ->withCount([
                "articles",
                "articles as articles_deleted_count" => function (Builder $builder) {
                    return $builder->onlyTrashed();
                }
            ])
            ->orderByDesc("articles_count")
            ->take(10)
            ->get();
        return view("backend.dashboard", ["user" => $request->user(), "users" => $users]);
    }
}

app/Http/Controllers/Backend/LoginController.php
<?php

namespace App\Http\Controllers\Backend;

use App\Http\Controllers\Controller;
use App\Http\Requests\Backend\LoginRequest;
use App\Models\User;
use Illuminate\Contracts\View\View;
use Illuminate\Http\RedirectResponse;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Hash;

class LoginController extends Controller
{

    public function form(): View
    {
        return view("backend.login.login");
    }

    public function login(LoginRequest $request): RedirectResponse
    {
        /** @var User $user */
        $user = User::query()->where("email", $request->validated("email"))->first();
        if (is_null($user) || !Hash::check($request->validated("password"), $user->password)) {
            return redirect()
                ->route("admin.form")
                ->withInput(["email" => $request->validated("email")])
                ->with("error", "Invalid credentials");
        }
        Auth::login($user);

        return redirect()->route("admin.dashboard");
    }

    public function logout(): RedirectResponse
    {
        Auth::logout();

        return redirect()->route("admin.form");
    }
}

app/Http/Controllers/Backend/RubricController.php
<?php

namespace App\Http\Controllers\Backend;

use App\Enums\Role;
use App\Http\Controllers\Controller;
use App\Http\Requests\Backend\Rubric\CreateRequest;
use App\Http\Requests\Backend\Rubric\DeleteRequest;
use App\Http\Requests\Backend\Rubric\RestoreRequest;
use App\Http\Requests\Backend\Rubric\UpdateRequest;
use App\Models\Rubric;
use Illuminate\Contracts\View\View;
use Illuminate\Database\Eloquent\Builder;
use Illuminate\Http\RedirectResponse;

class RubricController extends Controller
{
    public function index(): View
    {
        $user = auth()->user();

        $rubrics = Rubric::query()
            ->when($user->role === Role::KUBIK, function (Builder $builder) {
                return $builder->onlyTrashed();
            })
            ->where("name", "ilike", "%" . request("q", "") . "%")
            ->withCount("articles")
            ->latest()
            ->paginate(10)
            ->appends(["q" => request("q")]);

        return view("backend.rubric.index", compact("rubrics", "user"));
    }

    public function create(): View
    {
        return view("backend.rubric.create");
    }

    public function store(CreateRequest $request): RedirectResponse
    {
        $rubric       = new Rubric();
        $rubric->name = $request->validated("name");
        $rubric->save();

        return redirect()
            ->route("admin.rubric.index")
            ->with("success", "Rubric has been created successfully");
    }

    public function edit(Rubric $rubric): View
    {
        return view("backend.rubric.edit", compact("rubric"));
    }

    public function update(UpdateRequest $request, string $rubric): RedirectResponse
    {
        $rubric       = Rubric::find($rubric);
        $rubric->name = $request->validated("name");
        $rubric->save();

        return redirect()
            ->route("admin.rubric.edit", $rubric)
            ->with("success", "Rubric has been updated successfully");
    }

    public function destroy(DeleteRequest $request): RedirectResponse
    {
        $rubric = Rubric::find($request->validated("id"));
        $rubric->articles()->delete();
        $rubric->delete();

        return redirect()
            ->route("admin.rubric.index")
            ->with("success", "Rubric has been deleted successfully");
    }

    public function restore(RestoreRequest $request): RedirectResponse
    {
        Rubric::withTrashed()->find($request->validated("id"))->restore();

        return redirect()
            ->route("admin.rubric.index")
            ->with("success", "Rubric has been restored successfully");
    }
}

app/Http/Controllers/Backend/UserController.php
<?php

namespace App\Http\Controllers\Backend;

use App\Enums\Role;
use App\Http\Controllers\Controller;
use App\Http\Requests\Backend\User\CreateRequest;
use App\Http\Requests\Backend\User\UpdateRequest;
use App\Models\User;
use Illuminate\Contracts\View\View;
use Illuminate\Http\RedirectResponse;

class UserController extends Controller
{

    public function index(): View
    {
        $users = User::query()
            ->where("name", "ilike", "%" . request("q", "") . "%")
            ->latest()
            ->paginate(10)
            ->appends(["q" => request("q")]);

        return view("backend.user.index", compact("users"));
    }

    public function create(): View
    {
        return view("backend.user.create", [
            "roles" => Role::cases()
        ]);
    }

    public function store(CreateRequest $request): RedirectResponse
    {
        $user           = new User();
        $user->name     = $request->validated("name");
        $user->email    = $request->validated("email");
        $user->role     = $request->validated("role");
        $user->password = bcrypt($request->validated("password"));
        $user->save();

        return redirect()
            ->route("admin.user.index")
            ->with("success", "User has been created successfully");
    }

    public function edit(User $user): View
    {
        return view("backend.user.edit", [
            "user"  => $user,
            "roles" => Role::cases()
        ]);
    }

    public function update(UpdateRequest $request, string $user): RedirectResponse
    {
        $user        = User::find($user);
        $user->name  = $request->validated("name");
        $user->email = $request->validated("email");
        $user->role  = $request->validated("role");
        if ($request->filled("password")) {
            $user->password = bcrypt($request->validated("password"));
        }
        $user->save();

        return redirect()
            ->route("admin.user.index")
            ->with("success", "User has been updated successfully");
    }

    public function destroy(User $user): RedirectResponse
    {
        $user->delete();

        return redirect()
            ->route("admin.user.index")
            ->with("success", "User has been deleted successfully");
    }
}

resources/views/backend/dashboard.blade.php
@extends("backend.layout")

@section("title","Dashboard")

@section("content")
    <h1 style="margin-bottom: 30px">Hello, {{ $user->name }}</h1>
    @can("see-rubrics-users")
    <table class="table table-striped table-sm table-hover table-bordered">
        <thead>
        <tr>
            <th width="41%">Name</th>
            <th width="7%">Posted</th>
            <th width="7%">Deleted</th>
        </tr>
        </thead>
        <tbody>
        @forelse($users as $user)
            <tr>
                <td>{{ $user->name }}</td>
                <td>{{ $user->articles_count }}</td>
                <td><span>{{ $user->articles_deleted_count }}</span></td>
            </tr>
        @empty
            <tr>
                <td colspan="5">
                    <h3 class="text-center text-danger">
                        Nothing found for your request
                    </h3>
                </td>
            </tr>
        @endforelse

        </tbody>
    </table>
    @endcan
@endsection

resources/views/backend/layout.blade.php
<!DOCTYPE html>
<html lang="en" dir="ltr">
<head>
    <meta charset="utf-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta name="viewport" content="width=device-width, initial-scale=1"/>
    <title>@yield("title","Admin panel")</title>
    <!-- GOOGLE FONTS -->
    <link href="https://fonts.googleapis.com/css?family=Montserrat:400,500|Poppins:400,500,600,700|Roboto:400,500"
          rel="stylesheet"/>
    <link href="https://cdn.materialdesignicons.com/4.4.95/css/materialdesignicons.min.css" rel="stylesheet"/>

    <link id="sleek-css" rel="stylesheet" href="{{ asset("assets/css/sleek.css") }}"/>
</head>
<body class="header-fixed sidebar-fixed sidebar-dark header-light" id="body">
<!-- ====================================
——— WRAPPER
===================================== -->
<div class="wrapper">
    <!-- ====================================
      ——— LEFT SIDEBAR WITH OUT FOOTER
    ===================================== -->
    <aside class="left-sidebar bg-sidebar">
        <div id="sidebar" class="sidebar sidebar-with-footer">
            <!-- Aplication Brand -->
            <div class="app-brand">
                <a href="{{ route("frontpage") }}" title="Sleek Dashboard">
                    <svg
                        class="brand-icon"
                        xmlns="http://www.w3.org/2000/svg"
                        preserveAspectRatio="xMidYMid"
                        width="30"
                        height="33"
                        viewBox="0 0 30 33">
                        <g fill="none" fill-rule="evenodd">
                            <path class="logo-fill-blue" fill="#7DBCFF" d="M0 4v25l8 4V0zM22 4v25l8 4V0z"/>
                            <path class="logo-fill-white" fill="#FFF" d="M11 4v25l8 4V0z"/>
                        </g>
                    </svg>
                    <span class="brand-name text-truncate">{{ env("APP_NAME") }}</span>
                </a>
            </div>
            <!-- begin sidebar scrollbar -->
            <div class="" data-simplebar style="height: 100%;">
                <!-- sidebar menu -->
                <ul class="nav sidebar-inner" id="sidebar-menu">
                    <li>
                        <a class="sidenav-item-link" href="{{ route("admin.dashboard") }}">
                            <i class="mdi mdi-view-dashboard-outline"></i>
                            <span class="nav-text">Dashboard</span>
                        </a>
                    </li>
                    @can("see-rubrics-users")
                        <li>
                            <a class="sidenav-item-link" href="{{ route("admin.rubric.index") }}">
                                <i class="mdi mdi-view-dashboard-outline"></i>
                                <span class="nav-text">Rubrics</span>
                            </a>
                        </li>
                        <li>
                            <a class="sidenav-item-link" href="{{ route("admin.user.index") }}">
                                <i class="mdi mdi-view-dashboard-outline"></i>
                                <span class="nav-text">Users</span>
                            </a>
                        </li>
                    @elsecan("can-restore")
                        <li>
                            <a class="sidenav-item-link" href="{{ route("admin.rubric.index") }}">
                                <i class="mdi mdi-view-dashboard-outline"></i>
                                <span class="nav-text">Rubrics</span>
                            </a>
                        </li>
                    @endcan
                    <li>
                        <a class="sidenav-item-link" href="{{ route("admin.article.index") }}">
                            <i class="mdi mdi-view-dashboard-outline"></i>
                            <span class="nav-text">Articles</span>
                        </a>
                    </li>

                    <li>
                        <a class="sidenav-item-link" href="{{ route("admin.logout") }}">
                            <i class="mdi mdi-view-dashboard-outline"></i>
                            <span class="nav-text">Logout</span>
                        </a>
                    </li>
                </ul>
            </div>
        </div>
    </aside>
    <!-- ====================================
  ——— PAGE WRAPPER
  ===================================== -->
    <div class="page-wrapper">
        <!-- ====================================
        ——— CONTENT WRAPPER
        ===================================== -->
        <div class="content-wrapper">
            <div class="content">
                <div class="bg-white border rounded">
                    <div class="row">
                        <div class="col-12">
                            <div class="card card-default">
                                <div class="card-header">
                                    <h2>@yield("title")</h2>
                                </div>

                                <div class="card-body">
                                    @if (session("success"))
                                        <div class="alert alert-success">
                                            {{ session("success") }}
                                        </div>
                                    @endif
                                    @if ($errors->any())
                                        <div class="alert alert-danger">
                                            <ul>
                                                @foreach ($errors->all() as $error)
                                                    <li>{{ $error }}</li>
                                                @endforeach
                                            </ul>
                                        </div>
                                    @endif
                                    @yield("content")
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div> <!-- End Content -->
        </div> <!-- End Content Wrapper -->
    </div> <!-- End Page Wrapper -->
</div> <!-- End Wrapper -->
</body>
</html>