routes/web.php
<?php

use App\Http\Controllers\Backend\ArticleController;
use App\Http\Controllers\Backend\DashboardController;
use App\Http\Controllers\Backend\LoginController;
use App\Http\Controllers\Backend\RubricController;
use App\Http\Controllers\Backend\UserController;
use App\Http\Controllers\Frontend\FrontendController;
use Illuminate\Support\Facades\Route;

Route::get("/", [FrontendController::class, "index"])->name("frontpage");
Route::get("/rubric/{rubric}", [FrontendController::class, "rubric"])->name("rubric");
Route::get("/article/{article}", [FrontendController::class, "article"])->name("article");
Route::any("/search", [FrontendController::class, "search"])->name("search");
Route::post("/comment", [FrontendController::class, "storeComment"])->name("comment.store");

/**
 * admin
 */
Route::group(["prefix" => "admin", "as" => "admin."], function () {
    Route::get("", [LoginController::class, "form"])->name("form");
    Route::post("", [LoginController::class, "login"])->name("login");
    Route::group(["middleware" => ["admin"]], function () {
        Route::get("dashboard", DashboardController::class)->name("dashboard");
        Route::get("logout", [LoginController::class, "logout"])->name("logout");
        Route::resource("article", ArticleController::class)->except("show");
        Route::put("article/{article}/restore", [ArticleController::class, "restore"])->name("article.restore");
        Route::group(["middleware" => ["editor"]], function () {
            Route::resource("rubric", RubricController::class)->except("show");
            Route::put("rubric/{rubric}/restore", [RubricController::class, "restore"])->name("rubric.restore");
            Route::group(["middleware" => ["kubik"]], function () {
                Route::resource("user", UserController::class)->except("show");
            });
        });
    });
});

app/Models/User.php
<?php

namespace App\Models;

use App\Enums\Role;
use Illuminate\Database\Eloquent\Concerns\HasUuids;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Relations\HasMany;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Laravel\Sanctum\HasApiTokens;

/**
 * @property string id
 * @property string name
 * @property string email
 * @property string password
 * @property Role role
 *
 *
 * @method static find(string $string): User
 */
class User extends Authenticatable
{
    use HasApiTokens, HasFactory, Notifiable, HasUuids;

    protected $fillable = ["name", "email", "password", "role"];
    protected $hidden = ["password", "remember_token"];
    protected $casts = [
        "email_verified_at" => "datetime",
        "role"              => Role::class
    ];


    public function articles(): HasMany
    {
        return $this->hasMany(Article::class);
    }
}

app/Http/Controllers/Backend/ArticleController.php
<?php

namespace App\Http\Controllers\Backend;

use App\Enums\Role;
use App\Http\Controllers\Controller;
use App\Http\Requests\Backend\Article\CreateRequest;
use App\Http\Requests\Backend\Article\DeleteRequest;
use App\Http\Requests\Backend\Article\RestoreRequest;
use App\Http\Requests\Backend\Article\UpdateRequest;
use App\Models\Article;
use App\Models\Image;
use App\Models\Rubric;
use Illuminate\Contracts\View\View;
use Illuminate\Database\Eloquent\Builder;
use Illuminate\Http\RedirectResponse;
use Illuminate\Http\UploadedFile;
use Illuminate\Support\Facades\Storage;
use Illuminate\Support\Str;

class ArticleController extends Controller
{

    public function index(): View
    {
        $user = auth()->user();

        $articles = Article::query()
            ->when($user->role === Role::EDITOR, function (Builder $builder) use ($user) {
                return $builder->where("user_id", "=", $user->id);
            })
            ->when($user->role === Role::KUBIK, function (Builder $builder) {
                return $builder->onlyTrashed();
            })
            ->where(fn(Builder $builder) => $builder
                ->where("name", "ilike", "%" . request("q", "") . "%")
                ->orWhere("description", "ilike", "%" . request("q", "") . "%")
                ->orWhere("content", "ilike", "%" . request("q", "") . "%"))
            ->with(["rubric:id,name", "author:id,name"])
            ->withCount("comments")
            ->latest()
            ->paginate(20)
            ->appends(["q" => request("q")]);

        return view("backend.article.index", compact("articles", "user"));
    }


    public function create(): View
    {
        $rubrics = Rubric::query()->orderBy("name")->get();

        return view("backend.article.create", compact("rubrics"));
    }

    public function store(CreateRequest $request): RedirectResponse
    {
        $article              = new Article();
        $article->user_id     = auth()->id();
        $article->name        = $request->validated("name");
        $article->rubric_id   = $request->validated("rubric_id");
        $article->description = $request->validated("description");
        $article->content     = $request->validated("content");
        $article->save();

        $this->uploadImages($article, $request->file("images"));

        return redirect()
            ->route("admin.article.index")
            ->with("success", "Article has been created successfully");
    }


    public function edit(Article $article): View
    {
        $rubrics = Rubric::query()->orderBy("name")->get();
        $article->load("images");

        return view("backend.article.edit", compact("article", "rubrics"));
    }


    public function update(UpdateRequest $request, string $article): RedirectResponse
    {
        $article              = Article::find($article);
        $article->name        = $request->validated("name");
        $article->rubric_id   = $request->validated("rubric_id");
        $article->description = $request->validated("description");
        $article->content     = $request->validated("content");
        $article->save();

        $this->uploadImages($article, $request->file("images"));

        if (!is_null($request->get("cover"))) {
            $article->images()->update(["is_cover" => false]);
            $article->images()->find($request->get("cover"))->update(["is_cover" => true]);
        }

        return redirect()
            ->route("admin.article.edit", $article)
            ->with("success", "Article has been updated successfully");
    }


    public function destroy(DeleteRequest $request): RedirectResponse
    {
        Article::find($request->validated("id"))->delete();

        return redirect()
            ->route("admin.article.index")
            ->with("success", "Article has been deleted successfully");
    }


    public function restore(RestoreRequest $request): RedirectResponse
    {
        Article::withTrashed()->find($request->validated("id"))->restore();

        return redirect()
            ->route("admin.article.index")
            ->with("success", "Article has been restored successfully");
    }

    private function uploadImages(Article $article, ?array $files): void
    {
        if (is_null($files)) {
            return;
        }
        $storage = Storage::disk("images");

        $storage->makeDirectory($article->id);

        collect($files)->each(function (?UploadedFile $file) use ($storage, $article) {
            $fileName = Str::of(Str::random(24))->lower()->toString() . "." . $file->clientExtension();
            $storage->put($article->id . "/" . $fileName, $file->getContent());

            $image           = new Image();
            $image->filename = $fileName;

            $article->images()->save($image);
        });
    }
}

app/Http/Controllers/Backend/DashboardController.php
<?php

namespace App\Http\Controllers\Backend;

use App\Http\Controllers\Controller;
use App\Models\User;
use Illuminate\Contracts\View\View;
use Illuminate\Database\Eloquent\Builder;
use Illuminate\Http\Request;

class DashboardController extends Controller
{
    public function __invoke(Request $request): View
    {
        $users = User::query()
            ->withCount([
                "articles",
                "articles as articles_deleted_count" => function (Builder $builder) {
                    return $builder->onlyTrashed();
                }
            ])
            ->orderByDesc("articles_count")
            ->take(10)
            ->get();
        return view("backend.dashboard", ["user" => $request->user(), "users" => $users]);
    }
}

app/Http/Controllers/Backend/LoginController.php
<?php

namespace App\Http\Controllers\Backend;

use App\Http\Controllers\Controller;
use App\Http\Requests\Backend\LoginRequest;
use App\Models\User;
use Illuminate\Contracts\View\View;
use Illuminate\Http\RedirectResponse;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Hash;

class LoginController extends Controller
{

    public function form(): View
    {
        return view("backend.login.login");
    }

    public function login(LoginRequest $request): RedirectResponse
    {
        /** @var User $user */
        $user = User::query()->where("email", $request->validated("email"))->first();
        if (is_null($user) || !Hash::check($request->validated("password"), $user->password)) {
            return redirect()
                ->route("admin.form")
                ->withInput(["email" => $request->validated("email")])
                ->with("error", "Invalid credentials");
        }
        Auth::login($user);

        return redirect()->route("admin.dashboard");
    }

    public function logout(): RedirectResponse
    {
        Auth::logout();

        return redirect()->route("admin.form");
    }
}

app/Http/Controllers/Backend/RubricController.php
<?php

namespace App\Http\Controllers\Backend;

use App\Enums\Role;
use App\Http\Controllers\Controller;
use App\Http\Requests\Backend\Rubric\CreateRequest;
use App\Http\Requests\Backend\Rubric\DeleteRequest;
use App\Http\Requests\Backend\Rubric\RestoreRequest;
use App\Http\Requests\Backend\Rubric\UpdateRequest;
use App\Models\Rubric;
use Illuminate\Contracts\View\View;
use Illuminate\Database\Eloquent\Builder;
use Illuminate\Http\RedirectResponse;

class RubricController extends Controller
{
    public function index(): View
    {
        $user = auth()->user();

        $rubrics = Rubric::query()
            ->when($user->role === Role::KUBIK, function (Builder $builder) {
                return $builder->onlyTrashed();
            })
            ->where("name", "ilike", "%" . request("q", "") . "%")
            ->withCount("articles")
            ->latest()
            ->paginate(10)
            ->appends(["q" => request("q")]);

        return view("backend.rubric.index", compact("rubrics", "user"));
    }

    public function create(): View
    {
        return view("backend.rubric.create");
    }

    public function store(CreateRequest $request): RedirectResponse
    {
        $rubric       = new Rubric();
        $rubric->name = $request->validated("name");
        $rubric->save();

        return redirect()
            ->route("admin.rubric.index")
            ->with("success", "Rubric has been created successfully");
    }

    public function edit(Rubric $rubric): View
    {
        return view("backend.rubric.edit", compact("rubric"));
    }

    public function update(UpdateRequest $request, string $rubric): RedirectResponse
    {
        $rubric       = Rubric::find($rubric);
        $rubric->name = $request->validated("name");
        $rubric->save();

        return redirect()
            ->route("admin.rubric.edit", $rubric)
            ->with("success", "Rubric has been updated successfully");
    }

    public function destroy(DeleteRequest $request): RedirectResponse
    {
        $rubric = Rubric::find($request->validated("id"));
        $rubric->articles()->delete();
        $rubric->delete();

        return redirect()
            ->route("admin.rubric.index")
            ->with("success", "Rubric has been deleted successfully");
    }

    public function restore(RestoreRequest $request): RedirectResponse
    {
        Rubric::withTrashed()->find($request->validated("id"))->restore();

        return redirect()
            ->route("admin.rubric.index")
            ->with("success", "Rubric has been restored successfully");
    }
}

app/Http/Controllers/Backend/UserController.php
<?php

namespace App\Http\Controllers\Backend;

use App\Enums\Role;
use App\Http\Controllers\Controller;
use App\Http\Requests\Backend\User\CreateRequest;
use App\Http\Requests\Backend\User\UpdateRequest;
use App\Models\User;
use Illuminate\Contracts\View\View;
use Illuminate\Http\RedirectResponse;

class UserController extends Controller
{

    public function index(): View
    {
        $users = User::query()
            ->where("name", "ilike", "%" . request("q", "") . "%")
            ->latest()
            ->paginate(10)
            ->appends(["q" => request("q")]);

        return view("backend.user.index", compact("users"));
    }

    public function create(): View
    {
        return view("backend.user.create", [
            "roles" => Role::cases()
        ]);
    }

    public function store(CreateRequest $request): RedirectResponse
    {
        $user           = new User();
        $user->name     = $request->validated("name");
        $user->email    = $request->validated("email");
        $user->role     = $request->validated("role");
        $user->password = bcrypt($request->validated("password"));
        $user->save();

        return redirect()
            ->route("admin.user.index")
            ->with("success", "User has been created successfully");
    }

    public function edit(User $user): View
    {
        return view("backend.user.edit", [
            "user"  => $user,
            "roles" => Role::cases()
        ]);
    }

    public function update(UpdateRequest $request, string $user): RedirectResponse
    {
        $user        = User::find($user);
        $user->name  = $request->validated("name");
        $user->email = $request->validated("email");
        $user->role  = $request->validated("role");
        if ($request->filled("password")) {
            $user->password = bcrypt($request->validated("password"));
        }
        $user->save();

        return redirect()
            ->route("admin.user.index")
            ->with("success", "User has been updated successfully");
    }

    public function destroy(User $user): RedirectResponse
    {
        $user->delete();

        return redirect()
            ->route("admin.user.index")
            ->with("success", "User has been deleted successfully");
    }
}

resources/views/backend/user/create.blade.php
@extends("backend.layout")

@section("title","Create new user")

@section("content")
    <form action="{{ route("admin.user.store") }}" method="post">
        @csrf
        <div class="form-group">
            <label for="name">Name</label>
            <input type="text" name="name" class="form-control" id="name" placeholder="Enter name">
        </div>

        <div class="form-group">
            <label for="email">Email</label>
            <input type="text" name="email" class="form-control" id="email"
                   placeholder="Enter email">
        </div>
        <div class="form-group">
            <label for="role">Role</label>
            <select name="role" id="role" class="form-control">
                @foreach($roles as $role)
                    <option value="{{ $role->value }}">{{ $role->title() }}</option>
                @endforeach
            </select>
        </div>

        <div class="form-group">
            <label for="pass">Password</label>
            <input type="password" name="password" class="form-control" id="pass"
                   placeholder="Enter password">
        </div>

        <div class="form-group">
            <button type="submit" class="btn btn-success">
                Save
            </button>
        </div>
    </form>
@endsection

resources/views/backend/user/edit.blade.php
@extends("backend.layout")

@section("title","Update users' info")

@section("content")
    <form action="{{ route("admin.user.update", $user) }}" method="post">
        @method("put")
        @csrf
        <div class="form-group">
            <label for="exampleFormControlInput1">Name</label>
            <input type="text" name="name" class="form-control" value="{{ $user->name }}" placeholder="Enter name">
        </div>

        <div class="form-group">
            <label for="exampleFormControlInput1">Email</label>
            <input type="text" name="email" class="form-control" value="{{ $user->email }}" placeholder="Enter email">
        </div>
        <div class="form-group">
            <label for="role">Role</label>
            <select name="role" id="role" class="form-control">
                @foreach($roles as $role)
                    <option value="{{ $role->value }}" @if($role === $user->role) selected @endif>
                        {{ $role->title() }}
                    </option>
                @endforeach
            </select>
        </div>

        <div class="form-group">
            <label for="exampleFormControlInput3">Password</label>
            <input type="text" name="password" class="form-control"
                   placeholder="Enter password">
        </div>

        <div class="form-group">
            <button type="submit" class="btn btn-success">
                Save
            </button>
        </div>
    </form>
@endsection

resources/views/backend/user/index.blade.php
@extends("backend.layout")


@section("title","Users")


@section("content")
    <div class="row">
        <div class="col-10">
            <form class="form-inline" action="" method="get">
                <input type="text" name="q" value="{{ request("q") }}" class="form-control mb-2 mr-sm-2"
                       placeholder="Search request">
                <button type="submit" class="btn btn-primary mb-2">Search</button>
            </form>
        </div>
        <div class="col-2 text-right">
            <a href="{{ route("admin.user.create") }}" class="btn btn-success">Create new</a>
        </div>
    </div>
    <table class="table table-striped table-sm table-hover table-bordered">
        <thead>
        <tr>
            <th width="41%">Name</th>
            <th width="41%">Email</th>
            <th width="13%">Role</th>
            <th width="5%" colspan="2"></th>
        </tr>
        </thead>
        <tbody>
        @forelse($users as $user)
            <tr>
                <td>{{ $user->name }}</td>
                <td>{{ $user->email }}</td>
                <td>
                    <span class="badge rounded-pill {{ $user->role->color() }}">{{ $user->role->title() }}</span>
                </td>
                <td width="50px">
                    <a href="{{ route("admin.user.edit", $user) }}" class="btn btn-sm btn-primary">Edit</a>
                </td>
                <td width="50px">
                    <form action="{{ route("admin.user.destroy", $user) }}" method="post" class="form-inline">
                        @method("DELETE")
                        @csrf
                        <button type="submit" class="btn btn-sm btn-danger">Delete</button>
                    </form>
                </td>
            </tr>
        @empty
            <tr>
                <td colspan="5">
                    <h3 class="text-center text-danger">
                        Nothing found for your request
                    </h3>
                </td>
            </tr>
        @endforelse

        </tbody>
    </table>
    <div class="pagination pagination-seperated ">
        {{ $users->links() }}
    </div>
@endsection